#Copy Schemas and maps
jobs:
- job: buildAndVerify
  displayName: Build/Verification
  continueOnError: false
  pool: ${{parameters.pool}}

  workspace:
    clean: all

  steps:
  - task: AzureFileCopy@3
    displayName: 'Copy Files'
    inputs:
      sourcePath: ${{parameters.bicep.path}}
      additionalArgumentsForBlobCopy: '/Y /S /Pattern:*' 
      azureSubscription: ${{parameters.azureSubscription}}
      destination: AzureBlob
      storage: ${{parameters.storageAccount.name}}
      containerName: ${{parameters.storageAccount.containerName}}
      blobPrefix:  ${{parameters.storageAccount.blobPrefix}}
      outputStorageUri: storageAccountURI
      outputStorageContainerSasToken: storageAccountSASToken
      sasTokenTimeOutInMinutes: 60

  
  # Install the latest release of the bicep CLI binaries
  - task: AzureCLI@2
    displayName: Azure CLI Bicep Build
    inputs:
      azureSubscription: ${{parameters.azureSubscription}}
      scriptType: ps
      scriptLocation: inlineScript
      inlineScript: |
        $storageAccountCICD='{ ""url"" : ""$(storageAccountURI)${{parameters.storageAccount.blobPrefix}}"", ""sasToken"": ""$(storageAccountSASToken)"" }'
        az bicep build --file ${{parameters.bicep.path}}/${{parameters.bicep.templateFile}}
        #az deployment group what-if -f ${{parameters.bicep.path}}/${{parameters.bicep.templateFile}} -g ${{parameters.bicep.resourceGroup}} -p ${{parameters.bicep.path}}/${{parameters.bicep.parametersFile}} -p storageAccountCICD=$storageAccountCICD
   # what-if     
  - ${{each artifact in parameters.artifacts}}:
    - publish: ${{artifact.templateDirectory}}
      displayName: Publish Artifacts
      artifact: ${{artifact.name}}
