steps:
- task: AzureFileCopy@3
  displayName: 'Copy Files'
  inputs:
    SourcePath: $(Pipeline.Workspace)/${{parameters.artifactName}}
    azureSubscription: ${{parameters.azureSubscription}}
    Destination: AzureBlob
    storage: ${{parameters.storageAccount.name}}
    ContainerName: ${{parameters.storageAccount.containerName}}
    BlobPrefix:  ${{parameters.storageAccount.blobPrefix}}
    outputStorageUri: storageAccountURI
    outputStorageContainerSasToken: storageAccountSASToken
    sasTokenTimeOutInMinutes: 60
    
#Azure Resource Group Deployment task : https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops
- task: AzureResourceGroupDeployment@2
  displayName: 'Deploy ARM templates'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    action: Create Or Update Resource Group
    resourceGroupName: ${{parameters.resourceGroup}}
    location: ${{parameters.location}}
    templateLocation: Linked artifact
    csmFile: ${{parameters.masterTemplate}}
    csmParametersFile: ${{parameters.parametersFile}}
    overrideParameters: '
    -storageAccountCICD {
        "url": "$(storageAccountURI)${{parameters.storageAccount.blobPrefix}}",
        "sasToken": "$(storageAccountSASToken)"        
    }
    ' #'Correct syntax highlighting Visual Studio
    deploymentMode: 'Incremental'
