#Azure Resource Group Deployment task : https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment?view=azure-devops
- task: AzureResourceGroupDeployment@2
  name: 'Deploy ARM templates'
  inputs:
    azureSubscription: ${{parameters.azureSubscription}}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{parameters.resourceGroup}}
    location: ${{parameters.location}}
    templateLocation: 'Linked artifact'
    csmFile: '$(Pipeline.Workspace)/${{parameters.artifactName}}/orchestrator.json'
    csmParametersFile: ${{ format('{0}/{1}/{2}', '$(Pipeline.Workspace)', parameters.artifactName, parameters.parameterFile ) }}
    deploymentMode: 'Incremental'
