steps:
##Azure Key Vault Task: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-key-vault?view=azure-devops
- task: AzureKeyVault@1
  displayName: 'Azure Key Vault: ${{parameters.KeyVaultName}}'
  inputs:
   azureSubscription: ${{parameters.azureSubscription}}
   KeyVaultName: '${{parameters.KeyVaultName}}'
   SecretsFilter: ${{format('{0},{1}', parameters.azureSQLDBAdmin, parameters.azureSQLDBAdminSecretName)}}
   

##Azure SQL Database Deployment task:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops
- task: SqlAzureDacpacDeployment@1
  displayName: 'Deploy Azure SQL DacpacTask ${{parameters.databaseName}}'
  inputs:
   azureSubscription: '${{parameters.azureSubscription}}'
   ServerName: '${{parameters.sqlServerName}}'
   DatabaseName: '${{parameters.databaseName}}'
   SqlUsername: $(${{parameters.azureSQLDBAdmin}})
   SqlPassword: $(${{parameters.azureSQLDBAdminSecretName}})
   DacpacFile: ${{format('{0}/{1}','$(Pipeline.Workspace)', parameters.dacpacFile)}}
   AdditionalArguments: '${{parameters.AdditionalArguments}}'
   ipDetectionMethod: 'AutoDetect'
   deleteFirewallRule: trueS