# CI pipeline will be started on every branch
#Comment Code Block Ctrl+K+C / Ctrl+K+U
#Indent ctrl + [  or ctrl + ]

trigger:
  batch: true
  branches:
    include:
    - topic/*  #tempfortesting
    - main
    - master
    - release/*
  paths:
    include:
    - mdf-synapse/*
    exclude:
    - README.md
    - mdf-synapse/yaml/
  

variables:
  location: westeurope
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release')]

# Use build definition name for build/release numbers
name: $(BuildDefinitionName).$(Year:yy)$(DayOfYear)$(rev:.r)

# Call the build process template
stages:  
- stage: PreBuild
  condition: succeeded()
  jobs:
  # Deploy storageAccountCICD, this way mdf-synapse-mvp is a complete deployment in itself, although the blob could also be created manually or via Azure blueprints
  - job:
    displayName: Azure Deployment - Deploy storageAccountCICD Blob Storage - used for CICD Templates
    continueOnError: false
    pool:
      name: Azure pipelines
      vmImage: windows-2019
    workspace:
      clean: all
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment: Deploy CICD Templates Blob Storage'
      inputs:
        azureSubscription: Motion10-DnA-Dev (97ad1861-dc09-4b4c-83ac-28061d22e65c)
        action: Create Or Update Resource Group
        resourceGroupName: m10-synapseframework-dt
        location: $(location)
        csmFile: arm/storage-account/storage-account.json
        overrideParameters: '
            -storageAccount [{
                "kind": "StorageV2",
                "name": "stm10synfwcicd",
                "sku": {
                  "name": "Standard_LRS",
                  "tier": "Standard"
                }
            }]
            -general {
                "tags": {"Project": "mdf-m10-synapseframework-mvp"},
                "location": "westeurope"
            }
        '        
        deploymentMode: Incremental 

- stage: Build
  dependsOn: PreBuild
  condition: succeeded()
  jobs:   
  - template: ../mdf-synapse/yaml/pipeline/stages/build-stage.yml
    parameters:
      jobName: mdf-synapse  
      artifacts:
        - artifactName: arm-drop
          directory: mdf-synapse
      azureSubscription: Motion10-DnA-Dev (97ad1861-dc09-4b4c-83ac-28061d22e65c)
      environment: dt
      pool:
        name: Azure pipelines
        vmImage: windows-2019
      location: $(location)
      resourceGroup: m10-synapseframework-dt
      storageAccount:
        blobPrefix: $(Build.BuildNumber)
        containerName: build
        name: stm10synfwcicd
      templateDirectory: 
        arm: mdf-synapse/arm
        mdfs: mdf-synapse

- stage: DevTest
  dependsOn: Build
  condition: succeeded()
  jobs:  
  - template: ../mdf-synapse/yaml/pipeline/stages/release-stage.yml
    parameters:
      artifacts:       
        artifactName: arm-drop   
      azureSubscription: Motion10-DnA-Dev (97ad1861-dc09-4b4c-83ac-28061d22e65c)
      devOpsEnvironment: m10-dna-dev
      environment: dt         
      pool:
        name: Azure pipelines
        vmImage: windows-2019
      location: $(location)
      resourceGroup: m10-synapseframework-dt    
      storageAccount:
        blobPrefix: $(Build.BuildNumber)
        containerName: deploy
        name: stm10synfwcicd
      keyVault: kv-m10synframework-dt

- stage: Production
  dependsOn: DevTest
  condition: succeeded()
  jobs:  
  - template: ../mdf-synapse/yaml/pipeline/stages/release-stage.yml
    parameters:
      artifacts:       
        artifactName: arm-drop   
      azureSubscription: Motion10-DnA-Dev (97ad1861-dc09-4b4c-83ac-28061d22e65c)
      devOpsEnvironment: m10-dna-prd
      environment: p        
      pool:
        name: Azure pipelines
        vmImage: windows-2019
      location: $(location)
      resourceGroup: m10-synapseframework-p      
      storageAccount:
        blobPrefix: $(Build.BuildNumber)
        containerName: deploy
        name: stm10synfwcicd
      keyVault: kv-m10synframework-p
      TargetWorkspaceName: syn-m10synframework-p
      OverrideArmParameters: ' -key1 "NogAanPassen1"'