jobs:
  - deployment: 
    environment: ${{parameters.devOpsEnvironment}}
    continueOnError: false
    pool: ${{ parameters.pool }}
    workspace:
      clean: all              
        
    strategy: 
      runOnce:
        deploy:
          steps:
          #Release ARM   
          - template: steps/azure-resource-group-deployment-orchestrated-release.yml   # Template reference
            parameters:
              artifactName: ${{parameters.artifacts.artifactNameARM}}
              azureSubscription: ${{parameters.azureSubscription}}
              location: ${{parameters.location}}
              resourceGroup: ${{parameters.resourceGroup}}
              storageAccount: ${{parameters.storageAccount}}
              masterTemplate: ${{ format('{0}/{1}/{2}','$(Pipeline.Workspace)', parameters.artifacts.artifactNameMDF, 'orchestrator.json') }}
              parametersFile: ${{ format('{0}/{1}/{2}-{3}{4}', '$(Pipeline.Workspace)', parameters.artifacts.artifactNameMDF, 'parameters/orchestrator.parameters', parameters.environment, '.json') }}                                 

          #Publish ADF from JSON files, but only from the Main/Master/Release branch [environment: tst + prd]
          - ${{ if or(eq(parameters.environment, 'tst'), eq(parameters.environment, 'prd')) }}:
            - template: steps/publish-adf.yml
              parameters:
                artifactName: ${{parameters.artifacts.artifactNameMDF}}  
                azureSubscription: ${{parameters.azureSubscription}}
                datafactory: ${{parameters.datafactory}}             
                location: ${{parameters.location}}
                resourceGroup: ${{parameters.resourceGroup}}                                             
          
          #Publish SQL Databases from DACPAC
          - ${{ each database in parameters.databases }}: # Publish each database
            - template: steps/sql-dacpac-deployment.yml
              parameters: 
                azureSubscription: ${{parameters.azureSubscription}}
                KeyVaultName: ${{parameters.KeyVaultName}}
                sqlServerName: ${{ format('{0}{1}', parameters.sqlServerName, '.database.windows.net') }} 
                azureSQLDBAdmin: ${{parameters.azureSQLDBAdmin}}
                azureSQLDBAdminSecretName: ${{parameters.azureSQLDBAdminSecretName}}
                databaseName: ${{database.databaseName}}
                dacpacFile: ${{database.dacpacFile}}
                AdditionalArguments: '${{database.AdditionalArguments}}'

          # Trigger and Monitor ADF Pipeline run if stage is Test
          - ${{ if eq(parameters.environment, 'tst') }}: 
            - template: steps/azure-powershell-filepath.yml
              parameters:
                azureSubscription: ${{parameters.azureSubscription}}
                scriptFilePath: ${{parameters.datafactory.ps.scriptFilePath}}
                ScriptArguments: ${{parameters.datafactory.ps.scriptArguments}}