# CI pipeline will be started on every branch
#Comment Code Block Ctrl+K+C / Ctrl+K+U
#Indent ctrl + [  or ctrl + ]


trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    include:
    - <<azure-devops-folderpath>>
    exclude:
    - README.md

variables:
  location: westeurope

# Use build definition name for build/release numbers
name: $(BuildDefinitionName).$(Year:yy)$(DayOfYear)$(rev:.r)

# Call the build process template
stages:
- stage: Build
  jobs:
  - template: stages/build-stage.yml
    parameters:
      jobName: <<jobName>>
      artifactName: <<artifact-name>>
      azureSubscription: <<service-connection>>
      environment: dev
      pool:
        name: Azure pipelines
        vmImage: windows-2019
      location: $(location)
      resourceGroup: <<resource-group-name>>
      storageAccount:
        blobPrefix: $(Build.BuildNumber)
        containerName: build
        name: <<strorage-account-name>>
      templateDirectory: <<template-directory>>

# Call the release process template      
- stage: Development 
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: stages/release-stage.yml
    parameters:
      jobName: <<jobName>>
      artifactName: <<artifact-name>>
      azureSubscription: <<service-connection>>
      devOpsEnvironment: <<devops-environment>>
      environment: dev
      pool:
        name: Azure pipelines
        vmImage: windows-2019
      location: $(location)
      resourceGroup: <<resource-group-name>>
      storageAccount:
        blobPrefix: $(Build.BuildNumber)
        containerName: deploy
        name: <<strorage-account-name>>      
 
- stage: Test 
  dependsOn: Development
  condition: succeeded()
  jobs:
  - template: stages/release-stage.yml
    parameters:
      jobName: <<jobName>>
      artifactName: <<artifact-name>>
      azureSubscription: <<service-connection>>
      devOpsEnvironment: <<devops-environment>>
      environment: tst
      pool:
        name: Azure pipelines
        vmImage: windows-2019
      location: $(location)
      resourceGroup: <<resource-group-name>>
      storageAccount:
        blobPrefix: $(Build.BuildNumber)
        containerName: deploy
        name: <<strorage-account-name>>

- stage: Production 
  dependsOn: Test
  condition: succeeded()
  jobs:
  - template: stages/release-stage.yml
    parameters:
      jobName: <<jobName>>
      artifactName: <<artifact-name>>
      azureSubscription: <<service-connection>>
      devOpsEnvironment: <<devops-environment>>
      environment: prd
      pool:
        name: Azure pipelines
        vmImage: windows-2019
      location: $(location)
      resourceGroup: <<resource-group-name>>
      storageAccount:
        blobPrefix: $(Build.BuildNumber)
        containerName: deploy
        name: <<strorage-account-name>>