jobs:
  - deployment: 
    environment: ${{parameters.devOpsEnvironment}}
    continueOnError: false
    pool: ${{parameters.pool}}
    workspace:
      clean: all

    strategy: 
      runOnce:
        deploy:
          steps:
          #Release Bicep ARM Template deployment
          # - template: steps/azure-resource-group-deployment-release.yml
          #   parameters:
          #     azureSubscription: ${{parameters.azureSubscription}}
          #     location: ${{parameters.location}}
          #     bicep: ${{parameters.bicep}}

          #Release Bicep Az CLI deployment
          - template: steps/bicep-release.yml
            parameters:
              azureSubscription: ${{parameters.azureSubscription}}
              buildDefName: ${{parameters.buildDefName}}
              bicep: ${{parameters.bicep}}
